### ISSUE TITLE
bilibili插件无法显示和播放选中视频

### ISSUE THREAD

**Issue by lowy** [coslyk/moonplayer-plugins#6]
centos7 最新源码编译安装 除b站插件外其他都正常 不使用插件而是直接输入b站视频网址也正常 
![2019-01-17-18 28 48](https://user-images.githubusercontent.com/6565177/51312983-76599400-1a87-11e9-932f-c9e4bf648b05.png)

**Comment by coslyk** [comment]
谢谢反馈，已修复～
